name: Morning Love Letter

on:
  schedule:
    - cron: '30 5 * * *'
  workflow_dispatch:

jobs:
  send-love-mail:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout cod
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Instalare dependinte
        run: pip install requests

      - name: Executare script
        env:
          SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
          RECEIVER_EMAIL: ${{ secrets.RECEIVER_EMAIL_TEST }}
          SENDER_PASSWORD: ${{ secrets.SENDER_PASSWORD }}
        run: python main.py